artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_dir: artifacts/data_ingestion/samsum_dataset
  source_data: 'knkarthick/dialogsum'

data_validation:
  root_dir: artifacts/data_validation
  dataset_dir: artifacts/data_ingestion/samsum_dataset
  status_file: artifacts/data_validation/status.txt
  required_data_folders: ['train', 'validation', 'test']

data_transformation:
  root_dir: artifacts/data_transformation
  dataset_dir: artifacts/data_ingestion/samsum_dataset
  tokenized_dataset_dir: artifacts/data_transformation/tokenized_samsum_dataset
  tokenizer_checkpoint: &tokenizer_checkpoint google/flan-t5-base

model_training:
  root_dir: artifacts/model_training
  dataset_dir: artifacts/data_transformation/tokenized_samsum_dataset
  model_dir: artifacts/model_training/Summarization_Google_F5
  tokenizer_dir: artifacts/model_training/tokenizer
  model_checkpoint: *tokenizer_checkpoint

model_evaluation:
  root_dir: artifacts/model_evaluation
  dataset_dir: artifacts/data_ingestion/samsum_dataset     # test set is not transformed yet
  tokenized_test_dataset_dir: artifacts/model_evaluation/tokenized_test_samsum_dataset
  model_dir: artifacts/model_training/Summarization_Google_F5
  tokenizer_dir: artifacts/model_training/tokenizer
  metrics_file_name: artifacts/model_evaluation/metrics.csv
  base_model_checkpoint: *tokenizer_checkpoint
